name: JS Lint
on:
  pull_request:
    paths:
      - "**/.eslint*"
      - "**/.prettierrc.json"
      - "**/.editorconfig"
      - "**/package*.json"
      - "**/*.js"
  push:
    paths:
      - "**/.eslint*"
      - "**/.prettierrc.json"
      - "**/.editorconfig"
      - "**/package*.json"
      - "**/*.js"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.2
    - run: npm ci
    - run: npm run lint-ci
